# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wangyingjian/desktop/main/lib/csce441/glfw-3.3.2/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/share/cmake-3.16/Modules/WriteBasicConfigVersionFile.cmake))

/Users/wangyingjian/desktop/main/L07/L10/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/private/var/folders/x5/y108qr5n6vq19tf9hqbty_1r0000gn/T/AppTranslocation/1260E3F6-2FFE-4E1B-BE09-64548FCF2234/d/CMake.app/Contents/bin/cmake -H/Users/wangyingjian/desktop/main/L07/L10 -B/Users/wangyingjian/desktop/main/L07/L10/build
